INSERT INTO addresses VALUES (1, 'Warszawa', 'Krakowskie Przedmieście', '26/28', '00-927');
INSERT INTO addresses VALUES (10, 'Warszawa', 'Targowa przy Wileńskiej', '', '03-700');
INSERT INTO fields_of_study VALUES (1, 'Informatyka');
INSERT INTO fields_of_study VALUES (2, 'Matematyka Stosowana');
INSERT INTO fields_of_study VALUES (3, 'Metafizyka');
INSERT INTO fields_of_study VALUES (4, 'Chemia');
INSERT INTO fields_of_study VALUES (5, 'Medycyna');
INSERT INTO academies VALUES (1, 1, 1, 'Uniwersytet Warszawski', 'https://www.uw.edu.pl');
INSERT INTO accommodations VALUES (1, 'Warszawa Śródmieście', 10, 'pokój', 1800, 'https://adresowo.pl/o/n0w4a6');
INSERT INTO bus_stops VALUES (1, 'Targowa przy Wileńskiej');
INSERT INTO bus_lines VALUES (1, 1, 'N192');
INSERT INTO transports VALUES (1, 1, 'autobus');
INSERT INTO search_engine VALUES (1, 1, 1, 1);