insert into addresses values (1, 'Warszawa', 'Krakowskie Przedmieście', '26/28', '00-927');
insert into addresses values (10, 'Warszawa', 'Targowa przy Wileńskiej', '', '03-700');
insert into fields_of_study values (1, 'Informatyka');
insert into fields_of_study values (2, 'Matematyka Stosowana');
insert into fields_of_study values (3, 'Metafizyka');
insert into fields_of_study values (4, 'Chemia');
insert into fields_of_study values (5, 'Medycyna');
insert into academies values (1, 1, 1, 'Uniwersytet Warszawski', 'https://www.uw.edu.pl');
insert into accommodations values (1, 'Warszawa Śródmieście', 10, 'pokój', 1800, 'https://adresowo.pl/o/n0w4a6');
insert into bus_stops values (1, 'Targowa przy Wileńskiej');
insert into bus_lines values (1, 1, 'N192');
insert into transports values (1, 1, 'autobus');
insert into search_engine values (1, 1, 1, 1);